//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PourOver {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PourOver.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ID already appeared at line {0}..
        /// </summary>
        internal static string DuplicateId {
            get {
                return ResourceManager.GetString("DuplicateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token {{{0}}} appears {1} time(s) in &apos;{2}&apos; but appears {3} time(s) in &apos;{4}&apos;..
        /// </summary>
        internal static string FrequencyMismatch {
            get {
                return ResourceManager.GetString("FrequencyMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ’{0}’ has an invalid token: {1}.
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a closing brace (&apos;}&apos;).
        /// </summary>
        internal static string MissingClosingBrace {
            get {
                return ResourceManager.GetString("MissingClosingBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing an opening brace (&apos;{&apos;).
        /// </summary>
        internal static string MissingOpeningBrace {
            get {
                return ResourceManager.GetString("MissingOpeningBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token containing an opening brace (&apos;{&apos;).
        /// </summary>
        internal static string NestedOpeningBrace {
            get {
                return ResourceManager.GetString("NestedOpeningBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token {{{0}}} appears only in &apos;{1}&apos;..
        /// </summary>
        internal static string StrayToken {
            get {
                return ResourceManager.GetString("StrayToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of unique tokens is different: &apos;{0}&apos; has {1} token(s) but &apos;{2}&apos; has {3} token(s)..
        /// </summary>
        internal static string TypeNumberMismatch {
            get {
                return ResourceManager.GetString("TypeNumberMismatch", resourceCulture);
            }
        }
    }
}
